//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        public int Code { get; set; }
        public string StudentId { get; set; }
        public int Day { get; set; }
        public int Hour { get; set; }
        public bool Presence1 { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
