//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Code { get; set; }
        public int ClassCode { get; set; }
        public int Day { get; set; }
        public int Hour { get; set; }
        public string Subject { get; set; }
        public string TeacherId { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
